"""add intent to users

Revision ID: 050a32090a02
Revises: 83e1f6043b93
Create Date: 2026-06-30 18:01:01.970181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050a32090a02'
down_revision = '83e1f6043b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intent', sa.String(length=20), nullable=True))

    op.create_check_constraint(
        'chk_users_intent', 'users',
        "intent IS NULL OR intent IN ('ESTUDIANTE', 'RECLUTADOR')"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_users_intent', 'users', type_='check')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('intent')

    # ### end Alembic commands ###
