"""add_google_link_tokens_table

Revision ID: 186b5a2fe371
Revises: e89b2bf6614f
Create Date: 2026-08-01 18:06:04.759709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186b5a2fe371'
down_revision = 'e89b2bf6614f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # if_not_exists=True hace que el upgrade sea idempotente: si la tabla
    # ya existe (ej. tras un pg_restore que incluia el esquema de esta
    # revision), el upgrade no falla con DuplicateTable.
    op.create_table(
        'google_link_tokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('token_hash', sa.String(length=64), nullable=False),
        sa.Column('google_user_id', sa.String(length=255), nullable=False),
        sa.Column('pending_email', sa.String(length=254), nullable=False),
        sa.Column('pending_first_name', sa.String(length=100), nullable=True),
        sa.Column('pending_last_name', sa.String(length=100), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('used_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('token_hash'),
        if_not_exists=True,
    )
    # Usamos raw SQL para la creacion del indice porque IF NOT EXISTS no es
    # soportado via batch_alter_table en todas las versiones de Alembic.
    # Esto garantiza que el upgrade es idempotente cuando el indice ya existe
    # (ej. tras un pg_restore que incluia el esquema de esta revision).
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_google_link_tokens_token_hash "
        "ON google_link_tokens (token_hash)"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_google_link_tokens_token_hash")
    op.drop_table('google_link_tokens')
    # ### end Alembic commands ###
