"""add alert_type and threshold_percentage to user_alerts

Revision ID: 33f2045987f9
Revises: ee1b7b2d2464
Create Date: 2026-07-12 22:29:18.591440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f2045987f9'
down_revision = 'ee1b7b2d2464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_alerts', schema=None) as batch_op:
        # server_default='ABSOLUTE' hace backfill automático de las filas existentes,
        # que implícitamente son todas de umbral absoluto, sin violar el NOT NULL.
        batch_op.add_column(sa.Column('alert_type', sa.String(length=20), nullable=False, server_default='ABSOLUTE'))
        batch_op.add_column(sa.Column('threshold_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.alter_column('threshold_value',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_check_constraint(
            'chk_alerts_type',
            "alert_type IN ('ABSOLUTE', 'TREND')"
        )
        batch_op.create_check_constraint(
            'chk_alerts_threshold_matches_type',
            "(alert_type = 'ABSOLUTE' AND threshold_value IS NOT NULL) OR "
            "(alert_type = 'TREND' AND threshold_percentage IS NOT NULL)"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_alerts', schema=None) as batch_op:
        batch_op.drop_constraint('chk_alerts_threshold_matches_type', type_='check')
        batch_op.drop_constraint('chk_alerts_type', type_='check')
        batch_op.alter_column('threshold_value',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('threshold_percentage')
        batch_op.drop_column('alert_type')

    # ### end Alembic commands ###
